baseURL: "http://sphr2k.ga"
languageCode: "en-us"
title: "sphr2k.ga"
pygmentsstyle: 'monokai'
paginate: 6
social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
theme: novela
