name = "quickstart"
type = "webpack"
account_id = "456d2dfa5fb8925920dcfc42d77b3604"
workers_dev = true
route = ""
zone_id = "828dd6e87470719d37e6a22fc2d74eef"


[site]
bucket = "./public" # <-- Add your build directory name here!
entry-point = "workers-site"
